// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUfndyldR_vSJUQi5gWK9AzQBhUnJdXSA',
    appId: '1:394853422847:web:004e251c94f84978ed1eca',
    messagingSenderId: '394853422847',
    projectId: 'loginapp-a8cd6',
    authDomain: 'loginapp-a8cd6.firebaseapp.com',
    storageBucket: 'loginapp-a8cd6.firebasestorage.app',
    measurementId: 'G-LG5VKQCNSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcDDy_0p0nWjoSJ_0ZjfTZspMLKTMWKY',
    appId: '1:394853422847:android:1c4e7bb65c2d1db8ed1eca',
    messagingSenderId: '394853422847',
    projectId: 'loginapp-a8cd6',
    storageBucket: 'loginapp-a8cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeuDAZZuytmxIjwkBKKl1xQWh-3Uefd9I',
    appId: '1:394853422847:ios:c5512ff7fd67f8d5ed1eca',
    messagingSenderId: '394853422847',
    projectId: 'loginapp-a8cd6',
    storageBucket: 'loginapp-a8cd6.firebasestorage.app',
    iosBundleId: 'com.example.loginPopupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeuDAZZuytmxIjwkBKKl1xQWh-3Uefd9I',
    appId: '1:394853422847:ios:c5512ff7fd67f8d5ed1eca',
    messagingSenderId: '394853422847',
    projectId: 'loginapp-a8cd6',
    storageBucket: 'loginapp-a8cd6.firebasestorage.app',
    iosBundleId: 'com.example.loginPopupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUfndyldR_vSJUQi5gWK9AzQBhUnJdXSA',
    appId: '1:394853422847:web:b09c49e463da1c88ed1eca',
    messagingSenderId: '394853422847',
    projectId: 'loginapp-a8cd6',
    authDomain: 'loginapp-a8cd6.firebaseapp.com',
    storageBucket: 'loginapp-a8cd6.firebasestorage.app',
    measurementId: 'G-9BBQSG5DQN',
  );

}